In [1]:
import numpy as np

In [2]:
n1= np.array([1,2,3])
print(n1)

[1 2 3]


In [3]:
n2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
n0=np.zeros((1,3))
print(n0)

[[0. 0. 0.]]


In [5]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
n4=np.zeros((6,6))
n4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
n5=np.full((3,4),5)
n5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [8]:
n6=np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
n7=np.arange(10,50,5)
n7

array([10, 15, 20, 25, 30, 35, 40, 45])

In [11]:
n8=np.arange(10,21)
n8

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
n9 = np.arange(0,101,10)
n9

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [18]:
n10 = np.random.randint(0,2,50)
n10

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0])

In [20]:
n3.shape

(2, 3)

In [26]:
n11=np.array([[1,4,5,6,7,2,4,5,24,6,9],[1,2,3,1,2,3,45,3,6,5,22]])

In [27]:
n11.shape

(2, 11)

In [29]:
n11.shape = (11,2)
n11

array([[ 1,  4],
       [ 5,  6],
       [ 7,  2],
       [ 4,  5],
       [24,  6],
       [ 9,  1],
       [ 2,  3],
       [ 1,  2],
       [ 3, 45],
       [ 3,  6],
       [ 5, 22]])

# Uniendo arrays con Numpy

In [43]:
n1=np.array([1,2,3])
n2=np.array([7,8,9])
n3=np.array([10,11,12])

In [44]:
np.vstack((n1,n2,n3))

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
np.hstack((n1,n2))

array([1, 2, 3, 7, 8, 9])

In [45]:
np.column_stack((n1,n2,n3))

array([[ 1,  7, 10],
       [ 2,  8, 11],
       [ 3,  9, 12]])

# Intersección y diferencia con Numpy

In [47]:

n1=np.array([1,2,3,4])
n2=np.array([20,10,3,2,4])
np.intersect1d(n1,n2)

array([2, 3, 4])

In [48]:
np.setdiff1d(n1,n2)

array([1])

In [49]:
np.setdiff1d(n2,n1)

array([10, 20])

# Suma de arrays con Numpy

In [54]:
n1=np.array([1,3,5,7])
n2=np.array([2,4,6,8])
np.sum([n1,n2])

36

In [53]:
#suma elemento a elemnto de los diferentes arrays
np.sum([n1,n2],axis=0)

array([ 3,  7, 11, 15])

In [55]:
#regresa la suma de cada array
np.sum([n1,n2],axis=1)

array([16, 20])

# Matematicas

In [56]:
#suma basica
#suma 1 a cada elemeneto de cada array
n1=n1+1
n1

array([2, 4, 6, 8])

In [57]:
n1=n1-1
n1

array([1, 3, 5, 7])

In [58]:
#multiplica por 2 cada elemento del array
n1=n1*2
n1

array([ 2,  6, 10, 14])

In [59]:
n1=n1/2
n1

array([1., 3., 5., 7.])

# Funciones matematicas

In [60]:
#promedio
np.mean(n1)

4.0

In [61]:
#media
np.median(n1)

4.0

In [62]:
#desviación estándar
np.std(n1)

2.23606797749979

# Como guardar e importar datos
previamente se debe tener
import numpy as np

In [64]:
n1=np.array([10,20,30,40,50,60])
np.save('my_numpy', n1)

In [66]:
n2=np.load('my_numpy.npy')
n2

array([10, 20, 30, 40, 50, 60])